# -*- coding: utf-8 -*-
"""Consensus and Profile.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17Fuqjj8_HUjuX5KPBGI6sei3VR2EPL23

Consensus and Profile   https://rosalind.info/problems/cons/
"""

try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass

from google.colab import drive
drive.mount('/content/drive')

from Bio import SeqIO
#data=SeqIO.parse('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Consensus_and_Profile.txt', 'fasta') #small test data
data=SeqIO.parse('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_cons.txt','fasta') #data for submission
data=list(data)
s=[]
for n in range(len(data)):
  s.append(data[n].seq)

s

A=[]
C=[]
G=[]
T=[]
consensus=''
b=0 #number of sequence
for n in range(len(s[0])):
  a=0
  c=0
  g=0
  t=0
  for m in range(len(s)):
    if s[m][n] == 'A':
      a+=1
    elif s[m][n] == 'C':
      c+=1
    elif s[m][n] == 'G':
      g+=1
    elif s[m][n] == 'T':
      t+=1
  A.append(a)
  C.append(c)
  G.append(g)
  T.append(t)
  sym={a:"A",c:"C",g:"G", t:"T"}
  consensus=consensus+(sym.get(max(sym)))

print(consensus)
print('A:', *A)
print('C:', *C)
print('G:', *G)
print('T:', *T)
