# -*- coding: utf-8 -*-
"""Edit Distance.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SZvrPOzz6NfwQIyKOkjMMBH1AAM3TJlD

Edit Distance   https://rosalind.info/problems/edit/
"""

try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass

from google.colab import drive
drive.mount('/content/drive')

from Bio import SeqIO
#data=SeqIO.parse('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Edit_Distance.txt', 'fasta') #small test data
data=SeqIO.parse('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_edit.txt','fasta') #data for submission
data=list(data)
data

s1=data[0].seq
s1

s2=data[1].seq
s2

import numpy as np
matrix=np.zeros((len(s2)+1, len(s1)+1),dtype=int)
matrix[:,0]=np.arange(0, len(s2)+1, 1)
matrix[:1]=np.arange(0, len(s1)+1, 1)
matrix

for m in range(len(s1)):
  for n in range(len(s2)):
    if s2[n]==s1[m]:
      matrix[n+1][m+1] = matrix[n][m]
    else:
      matrix[n+1][m+1]=min(matrix[n+1][m], matrix[n][m+1], matrix[n][m])+1
ed= matrix[len(s2)][len(s1)]

ed