# -*- coding: utf-8 -*-
"""Enumerating Gene Orders.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Oo41oMhyCJXo36quzGuT68oRgeqtZRjV

Enumerating Gene Orders   https://rosalind.info/problems/perm/
"""

import itertools
N=6
list_num=[]
for n in range(1, N+1):
  list_num.append(n)

perm=itertools.permutations(list_num)
perm=list(perm)
print(len(perm))
for m in range(len(perm)):
  print(*perm[m])