# -*- coding: utf-8 -*-
"""Finding a Motif in DNA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XiSqjQyN2R4ZeRKfJhhsU2Rkb7J4ww77

https://rosalind.info/problems/subs/
"""

from google.colab import drive
drive.mount('/content/drive')

#DNA=open('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Finding_a_Motif_in_DNA.txt') #small test data
DNA=open('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_subs.txt','r') #data for submission
DNA=DNA.read().split('\n')
motif=DNA[1]
DNA=DNA[0]

print(DNA)
print(motif)

DNA[0:4]

a=0
b=len(motif)
for n in range (0,(len(DNA)-len(motif)-1)):
  if DNA[a:b]==motif:
    loca=a+1
    a=a+1
    b=b+1
    print(loca)
  else:
    a=a+1
    b=b+1