# -*- coding: utf-8 -*-
"""Computing GC Content.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bRgBVeUqr4syjxAUel3YeRlgDUzKDoj-

https://rosalind.info/problems/gc/
"""

from google.colab import drive
drive.mount('/content/drive')

try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass

from Bio import SeqIO
from Bio.SeqUtils import gc_fraction
#data=SeqIO.parse("/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Computing_GC_Content.txt", "fasta") #test small data
data=SeqIO.parse("/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_gc.txt", "fasta") #test big data
data=list(data)

data
# print(data[1].id)
# print(data[1].seq)

seq_GC=[]
seq_name=[]
for n in range (0, len(data)):
  seq_GC.append(gc_fraction(data[n].seq))
  seq_name.append(data[n].id)
print(seq_GC)
print(seq_name)
max(seq_GC)
data[seq_GC.index(max(seq_GC))].id

print(data[seq_GC.index(max(seq_GC))].id)
print(str("%.3f" % ((max(seq_GC))*100)),'%', sep='')
#print((max(seq_GC))*100)
