# -*- coding: utf-8 -*-
"""Overlap Graphs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tELG2kbQF9EOBjpTUxbHn8_rVQxTFGFj

https://rosalind.info/problems/grph/
"""

from google.colab import drive
drive.mount('/content/drive')

try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass

from Bio import SeqIO

#data=SeqIO.parse("/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Overlap_Graphs.txt", "fasta") #test small data
data=SeqIO.parse("/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_grph.txt", "fasta") #test big data
data=list(data)

print(data)
print(data[0].id)
print(data[0].seq)
print((data[0].seq)[len(data[0].seq)-3:len(data[0].seq)])
(print(len(data)))

print((data[0].seq)[len(data[0].seq)-3:len(data[0].seq)])
print(data[1].seq[0:3].find(((data[0].seq)[len(data[0].seq)-3:len(data[0].seq)])))

print(data[1].seq[0:3])

a=0
for n in range (len(data)):
  for m in range (len(data)-1):
    if (data[a].seq)[len(data[a].seq)-3:len(data[a].seq)] == data[m+1].seq[0:3] and a!=m+1:
      print(data[a].id, data[m+1].id)
  a=a+1