# -*- coding: utf-8 -*-
"""Counting_Point_Mutations.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mvK_fZXJrNOvtMnPYnBNvMex3SEPY67m

https://rosalind.info/problems/hamm/
"""

from google.colab import drive
drive.mount('/content/drive')

#data=open('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Counting_Point_Mutations.txt','r') #small test data
data=open('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_hamm.txt','r') #data for submission
data=data.read().split('\n')
data

count=0
for n in range (0, len(data[0])):
  if data[0][n]==data[1][n]:
    continue
  else:
    count=count+1

print(count)
