# -*- coding: utf-8 -*-
"""Calculating Expected Offspring.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wHvHiUJA4pLV1lrArMJp80y-GqTNyzVf

Calculating Expected Offspring   https://rosalind.info/problems/iev/
"""

# 1.AA-AA
# 2.AA-Aa
# 3.AA-aa
# 4.Aa-Aa
# 5.Aa-aa
# 6.aa-aa

c=[18357, 16692, 19915, 17400, 17217, 18306]

total=sum(c)

print(2*(1*c[0] + 1*c[1] + 1*c[2] + 0.75*c[3] + 0.5*c[4]))
