# -*- coding: utf-8 -*-
"""Finding a Shared Motif.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LeGHXIbbwKAMreJubYUEdJKUgw2_iWVC

https://rosalind.info/problems/lcsm/


**Longest Common Substring**
"""

from google.colab import drive
drive.mount('/content/drive')

try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass

from Bio import SeqIO

#data=SeqIO.parse('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Finding_a_Shared_Motif.txt', 'fasta')#small test data
data=SeqIO.parse('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_lcsm.txt','fasta') #data for submission

data=list(data)

sequence=[]
for m in range (len(data)):
  sequence.append(data[m].seq)

sequence

#code for explaining the loop
#shortest='ATACA'
#for length in range(5, 0, -1):
 # print('.................')
  #print(length)
  #print("==================")
  #for start in range(5 - length + 1):
   # sub = shortest[start:start+length]
   # print(sub)
   # print(start)
   # print('--------------')

#method 1
#find the shortest seq, and find if the shortest seq in all seq
#else length of shortest seq -1, then repeat unitl find a match seq
def longestCommon(seqs):
  shortest = min(seqs, key=len)
  for length in range(len(shortest), 0, -1): #range(start, stop, step)
    for start in range(len(shortest) - length + 1):
      sub = shortest[start:start+length]
      #print(sub)
      if all(data.seq.find(sub) >= 0 for seq in seqs):
         #all() on a generator expression allows the "is this sub in every sequence?" check to be done compactly and lazily in-line
         ##find() method returns the lowest index or first occurrence of the substring if it is found in a given string.
         ##If it’s not found then it returns -1
        return sub
  return ""

#seqs=sequence
#seqs=['GATTACA','TAGACCA','ATACA']
print(longestCommon(data))

#method 2
def long_substr(data):
    substr = ''
    if len(data) > 1 and len(data[0]) > 0:
      for i in range(len(data[0])):
        for j in range(len(data[0])-i+1):
          if j > len(substr) and all(data[0][i:i+j] in x for x in data):
            substr = data[0][i:i+j]
    return substr

#data=sequence

#data=['GATTACA','TAGACCA','ATACA']

print(long_substr(data))

seqs=['GATTACA','TAGACCA','ATACA']
for seq in seqs:
  #if seq.find('TACA') >= 0:
  print(seq.find('ACA'))
