# -*- coding: utf-8 -*-
"""Locating Restriction Sites.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1onzT9lKIrYa_3s-hcXeqFnuBkWxfwagl

Locating Restriction Sites https://rosalind.info/problems/revp/
"""

try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass

from google.colab import drive
drive.mount('/content/drive')

from Bio import SeqIO
#data=SeqIO.read('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Locating_Restriction_Sites.txt', 'fasta') #small test data
data=SeqIO.read('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_revp.txt','fasta') #data for submission

data

seq_rev=data.seq.reverse_complement()
seq_rev

def LRS (data):
  pair=[]
  for length in range(len(data.seq), 0, -1):
    for start in range(len(data.seq) - length + 1):
      if data.seq[start:start+length]==data.seq[start:start+length].reverse_complement() and 4<=len(data.seq[start:start+length])<=12:
        pair.append((start+1,len(data.seq[start:start+length])))
        pair.sort()
  return pair

#LRS(data)

for n in range(len(LRS(data))):
  print(LRS(data)[n][0], LRS(data)[n][1])