# -*- coding: utf-8 -*-
"""Finding a Protein Motif.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13WJ67ht9A74SLxl2E9W0fu8QmDioncsr
"""

try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass

from google.colab import drive
drive.mount('/content/drive')

#IDs=open('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Finding_a_Protein_Motif.txt') #small test data
IDs=open('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_mprt.txt')  #data for submission
IDs=IDs.read().split('\n')
IDs.remove("")
IDs

IDs_list=[]
import re
from re import split
for i in range(len(IDs)):
  IDs_new=split(r'[^0-9a-zA-Z]+', IDs[i])
  IDs_list.append(IDs_new[0])
IDs_list

import requests as r
from Bio import SeqIO
from io import StringIO

pSeq_list=[]
for n in range(len(IDs_list)):
  cID=IDs_list[n]

  baseUrl="http://www.uniprot.org/uniprot/"
  currentUrl=baseUrl+cID+".fasta"

  response = r.post(currentUrl)

  cData=''.join(response.text)

  Seq=StringIO(cData)

  pSeq=list(SeqIO.parse(Seq,'fasta'))

  pSeq_list.append(pSeq[0].seq)

pSeq_list

count=0

motif  = re.compile('(?=(N[^P][S|T][^P]))') #have to consider to include overlaps
for n in range(len(pSeq_list)):
  position=[]

  #if re.finditer(r'(N)([^P])(S|T)([^P])', str(pSeq_list[n])) is False:

  for match in re.finditer(motif, str(pSeq_list[n])):
    position.append(match.start()+1)

  if len(position)>0:
    print(IDs[count])
    print(*position)
  count+=1
