# -*- coding: utf-8 -*-
"""Open Reading Frames.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kT07rS7ObMbXmGJQo1Lch5Kq1JNf0A8w

Open Reading Frames
https://rosalind.info/problems/orf/
"""

from google.colab import drive
drive.mount('/content/drive')

try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass

from Bio import SeqIO
#data=SeqIO.read('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Open_Reading_Frames.txt', 'fasta') #small test data
data=SeqIO.read('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_orf.txt','fasta') #data for submission

data



import re
def ORF (data):
  potein_list_stop_true=[]
  potein_list_stop_false=[]

  index=[m.start() for m in re.finditer('ATG', str(data.seq))]

  for n in range (len(index)):
    potein_stop_true=data.seq[index[n]:].translate(to_stop=True, stop_symbol="*")
    potein_list_stop_true.append(str(potein_stop_true))

    potein_stop_false=data.seq[index[n]:].translate()
    potein_list_stop_false.append(str(potein_stop_false))

  seq_rev=data.seq.reverse_complement()
  index_rev=[a.start() for a in re.finditer('ATG', str(seq_rev))] #[5, 70, 90]
  for b in range (len(index_rev)):
    #seq_new=seq_rev[index_rev[b]:]
    potein_rev_stop_true=seq_rev[index_rev[b]:].translate(to_stop=True, stop_symbol="*")
    potein_list_stop_true.append(str(potein_rev_stop_true))

    potein_rev_stop_false=seq_rev[index_rev[b]:].translate()
    potein_list_stop_false.append(str(potein_rev_stop_false))

  potein_list_stop_true= list(set(potein_list_stop_true))
  potein_list_stop_false  = [sub for sub in potein_list_stop_false if not any(ele in sub for ele in '*')]
  answer=[sub for sub in potein_list_stop_true if not any(ele in sub for ele in potein_list_stop_false)]

  return answer



print('\n'.join(ORF(data)))