# -*- coding: utf-8 -*-
"""Introduction to Random Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qwjn692gihIZ_XuGGLv2frzZFDpQpB9C

Introduction to Random Strings   https://rosalind.info/problems/prob/
"""

from google.colab import drive
drive.mount('/content/drive')

#data=open('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Introduction_to_Random_Strings.txt') #small test data
data=open('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_prob.txt')  #data for submission
data=data.read().split('\n')
data

s=data[0]
s

A=data[1].split()
A

import math

GC=0
AT=0
for n in range(len(s)):
  if s[n]=='C' or s[n]=='G':
    GC+=1
  else:
    AT+=1


B=[]

for m in range(len(A)):
  B.append((math.log10((float(A[m])/2)**GC))+(math.log10((((1-(float(A[m])))/2)**AT))))

print(*B)
