# -*- coding: utf-8 -*-
"""Translating RNA into Protein.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lD3ZQ6hVI_iY6f6-UxPgRSik0fL9mveF

https://rosalind.info/problems/prot/
"""

from google.colab import drive
drive.mount('/content/drive')

try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass

from Bio.Seq import Seq
#RNA=open('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/Translating_RNA_into_Protein.txt','r') #small test data
RNA=open('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_prot.txt','r') #data for submission
RNA=Seq(RNA.read())
RNA

print(RNA.translate(to_stop=True))



