# -*- coding: utf-8 -*-
"""Rabbits and Recurrence Relations .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XuZX-ppdU7OyBl001Ay8qQR8WSXw6NjD

Rabbits and Recurrence Relations   https://rosalind.info/problems/fib/

---
 F1=F2=1


---

Fn=Fn−1+Fn−2
"""

n=36
k=5
a=1
b=1

for n in range(1, n-1):
  a, b = b, a*k+b

print(b)