# -*- coding: utf-8 -*-
"""RNA Splicing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zxqU8IdyMfoXK5X1T_lX3OoOUfmG8Dh4

RNA Splicing   https://rosalind.info/problems/splc/
"""

try:
    import google.colab
    # Running on Google Colab, so install Biopython first
    !pip install biopython
except ImportError:
    pass

from google.colab import drive
drive.mount('/content/drive')

from Bio import SeqIO
#data=SeqIO.parse('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Sample_Dataset/RNA_Splicing.txt', 'fasta') #small test data
data=SeqIO.parse('/content/drive/MyDrive/Colab_Notebooks/Rosalind/Dataset/rosalind_splc.txt','fasta') #data for submission
data=list(data)
data

data[0].seq

def RS (data):
  intron_list=[]
  for n in range(len(data)-1):
    intron_list.append(data[n+1].seq)

  for intron in intron_list:
    data[0].seq = data[0].seq.replace(intron, '')

  protein=data[0].seq.translate(to_stop=True)
  return protein

print(RS(data))
 
